[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Area"
authors = [{name = "Graziella", email = "graziella@area"}]
dynamic = ["version", "description"]
